chromosomes:
  - "chrY"
samples:
  - chrYv1.3
#smkdir: /data/home/wangbo/software/CenMAP/workflow
concat_asm:
  # Expects {input_dir}/{sm}/*.gz
  input_dir: "test/data/assemblies"
  output_dir: "results_chrYv1.3/assemblies/combined"
  mem: 100GB

align_asm_to_ref:
  # Output dir set to results_chrYv1.3
  reference: "test/data/reference/T2T-CHM13v2.fasta"
  threads: 96
  mem: 100GB

extract_ref_hor_arrays:
  output_dir: "results_chrYv1.3/ref_hor_arrays"
  # Add bp to extend edges of HOR array for alignment. In addition to default 500kbp.
  added_bases: 500_000

ident_cen_ctgs:
  comb_assemblies_dir: "data/assemblies/combined"
  output_dir: "results_chrYv1.3/cens"
  ref_cens_regions: "data/annotations/chm13_v2.0_cenSat_Annotations_HORs.maxmin.500kbp.bed"
  ref_cens_monomeric_regions: "data/annotations/chm13_v2.0_monomeric_p-qarm_only.bed"

dna_brnn:
  output_dir: "results_chrYv1.3/dna_brnn"
  # https://github.com/lh3/dna-nn/tree/master/models
  model: "data/models/attcc-alpha.knm"
  # File with dna-brnn run on t2t-chm13 ref. Avoids running rule to generate.
  # Optional.
  ref_alr_file: "data/annotations/chm13_cens.trimmed.bed"
  threads: 96
  mem: 100GB
  thr_file: "config/dnabrnn_thresholds.json"
  full_alr_thr_file: "config/dnabrnn_full_alr_region_thresholds.json"

new_cens:
  output_dir: "results_chrYv1.3/cens_new"


repeatmasker:
  ref_repeatmasker_chrY_output: data/annotations/cenSat_Annotations_HORs.maxmin.v2.0.chrY.500kbp.fa.out
  ref_repeatmasker_output: data/annotations/chm13_chm1_cens_v21.trimmed.fa.noheader.out
  config_censtats_status: "config/censtats.json"
  threads: 96
  output_dir: "results_chrYv1.3/repeatmasker"

humas_hmmer:
  # Dir where split cens placed.
  input_dir: "results_chrYv1.3/humas_hmmer/cens"
  output_dir: "results_chrYv1.3/humas_hmmer"
  # NOTE: If providing 150 cores and num_threads=30, a max of 5 are run concurrently.
  threads: 64
  model: "data/models/AS-HORs-hmmer3.0-170921.hmm"
hmm_profile: "/data/home/wangbo/software/CenMAP/workflow/rules/Snakemake-HumAS-HMMER-main/data/AS-HORs-hmmer3.3.2-120124.hmm"

plot_hor_stv:
  output_dir: "results_chrYv1.3/hor_stv"
  chm1_stv: "data/annotations/AS-HOR-vs-chm1_cens_v21.stv_row.all.bed"
  chm13_stv: "data/annotations/AS-HOR-vs-chm13_cens_v18.correctcoords.stv_row.all.bed"
  sat_annot_colors: "config/repeatmasker_sat_annot_colors.json"

calculate_hor_length:
  chm1_hor_lengths: "data/annotations/chm1_hor_length.tsv"
  chm13_hor_lengths: "data/annotations/chm13_hor_length.tsv"
  output_dir: "results_chrYv1.3/calculate_hor_length"

count_complete_cens:
  output_dir: "results_chrYv1.3/count_complete_cens"
  plot_lbl: null
  plot_color: "#DA8B26"

moddotplot:
  input_dir: null
  output_dir: "results_chrYv1.3/moddotplot"
  mem: 100GB
  window: 5000

